-- Secure server-only OAuth token storage for Mercado Libre.
-- Token values are encrypted by the application with AES-256-GCM before persistence.
create table if not exists public.provider_oauth_tokens (
  provider text primary key,
  access_token_ciphertext text not null,
  refresh_token_ciphertext text,
  token_type text not null default 'Bearer',
  expires_at timestamptz,
  scope text,
  external_user_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_oauth_tokens_provider_check check (provider ~ '^[a-z0-9_-]{2,40}$')
);

alter table public.provider_oauth_tokens enable row level security;
revoke all on table public.provider_oauth_tokens from anon, authenticated;
grant all on table public.provider_oauth_tokens to service_role;

comment on table public.provider_oauth_tokens is
  'Server-only encrypted OAuth credentials. Never expose through browser clients.';
comment on column public.provider_oauth_tokens.access_token_ciphertext is
  'AES-256-GCM ciphertext generated by the application; never plaintext.';
comment on column public.provider_oauth_tokens.refresh_token_ciphertext is
  'AES-256-GCM ciphertext generated by the application; never plaintext.';
